version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    restart: always
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=cameron.alford@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  static_website:
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static_website.rule=Host(`alicam.org`)"
      - "traefik.http.routers.static_website.entrypoints=web"
      - "traefik.http.routers.static_website.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.static_website_tls.rule=Host(`alicam.org`)"
      - "traefik.http.routers.static_website_tls.entrypoints=websecure"
      - "traefik.http.routers.static_website_tls.tls.certresolver=myresolver"
      - "traefik.http.routers.static_website_tls.tls.domains[0].main=alicam.org"
      - "traefik.http.routers.static_website_tls.tls.domains[0].sans=*.alicam.org"

volumes:
  letsencrypt:
